### ISSUE TITLE
Issue 1: User can search for spray names

### ISSUE THREAD

**Issue by jooliecodes** [julieluangpraxay/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can search for the in-game spray names in the search bar. 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Users can type in the search bar to search for a specific spray in VALORANT.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-08-17 at 4 44 37 PM](https://github.com/julieluangpraxay/ajax-project/assets/130415142/1557ec12-3efa-48bc-86d4-66789b6327b6)
![Screenshot 2023-08-17 at 4 44 27 PM](https://github.com/julieluangpraxay/ajax-project/assets/130415142/19ae14fd-247d-4bd5-901b-6845516c033e)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create enter page and add background image and button to enter.
- [x] View swap to home page after button is clicked.
- [x] Create event listener for button when it is clicked in main.js.
- [x] Create a header section in your HTML and a new HTML page.
- [x] Add the background image to the page.
- [x] Add header section and style with CSS.
- [x] Add a search icon and heart icon in the header.
- [x] Add a search bar component to the webpage.
- [x] Create an HTML input element to serve as the search bar.
- [x] Apply CSS styles to the search bar for sizing and positioning.
- [x] Implement a button or submit action to initiate the search.
- [x] Define a JavaScript function to handle API requests.
- [x] Handle API responses and error cases.
- [x] Dynamically update the search results section with data from the API response.

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
