### ISSUE TITLE
Issue 2 : User can add sprays to a favorites list

### ISSUE THREAD

**Issue by jooliecodes** [julieluangpraxay/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can favorite any spray.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can favorite any spray they like and it will add their favorite spray to a list.
 ## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-08-18 at 2 56 36 PM](https://github.com/julieluangpraxay/ajax-project/assets/130415142/6bbe3007-cea4-4bff-8660-2714f02d4004)
![Screenshot 2023-08-18 at 2 51 25 PM](https://github.com/julieluangpraxay/ajax-project/assets/130415142/55e08cd5-629c-418e-b89e-32cc10219280)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a click event listener when the user clicks on the heart icon.
- [x] Turn the heart icon to solid red once the heart icon is clicked.
- [x] Create a new array value in the data object in data.js called "favorites".
- [ ] Stores the clicked spray in the favorites array in the data object.
- [ ] Assign the favoritedSpray into the data model so that more favorites can be added to the list and stored.
- [ ] Include a conditional statement that checks to see if there is a JSON data model stored in localStorage.
- [ ] If there is, parse it and assign it to the initial data variable so that the user can continue adding favorites to the pre-existing data model.
- [ ] Test the app by submitting some new favorites and then reloading the page to confirm that the data model is being saved to localStorage before each page reloads, each new favorite spray object is receiving an incrementing favoritedSprays property.
- [ ] Add an event listener to the top logo so the user can go back to the home page.

- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
